# Generated by Django 4.0 on 2022-01-02 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netvis', '0003_rename_scrip_stage_incoming_srcip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage_incoming',
            old_name='icmpnode',
            new_name='icmpcode',
        ),
    ]
