# Generated by Django 4.0 on 2021-12-31 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netvis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='netvis_tran_src_ip__b08f25_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='netvis_tran_dst_ip__6495bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='netvis_tran_src_ip__be01b1_idx',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='dst_ip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_ip_id', to='netvis.ip_address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='src_ip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_ip_id', to='netvis.ip_address'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['src_ip_id', 'dst_ip_id', 'protocol'], name='netvis_tran_src_ip__8c8cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['dst_ip_id'], name='netvis_tran_dst_ip__768402_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['src_ip_id', 'dst_ip_id', 'srcport', 'dstport'], name='netvis_tran_src_ip__e4517d_idx'),
        ),
    ]
