# Generated by Django 4.0 on 2022-01-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netvis', '0002_remove_transaction_netvis_tran_src_ip__b08f25_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage_incoming',
            old_name='scrip',
            new_name='srcip',
        ),
    ]
