# Generated by Django 4.0 on 2022-01-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netvis', '0004_rename_icmpnode_stage_incoming_icmpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip_address',
            name='ip_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
