# Generated by Django 4.0 on 2022-01-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netvis', '0005_alter_ip_address_ip_id_alter_transaction_trans_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip_address',
            name='ip_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='trans_id',
        ),
        migrations.AddField(
            model_name='ip_address',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
