# Generated by Django 4.0 on 2022-01-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netvis', '0006_remove_ip_address_ip_id_remove_transaction_trans_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage_incoming',
            name='dstport',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='stage_incoming',
            name='srcport',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='dstport',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='srcport',
            field=models.CharField(max_length=5),
        ),
    ]
