# Generated by Django 4.0 on 2022-01-17 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netvis', '0007_alter_stage_incoming_dstport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='dst_ip_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dst_ip_id', to='netvis.ip_address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='src_ip_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='src_ip_id', to='netvis.ip_address'),
        ),
    ]
