# Generated by Django 4.0 on 2022-01-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netvis', '0008_alter_transaction_dst_ip_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transaction',
            new_name='Events',
        ),
        migrations.RenameModel(
            old_name='ip_address',
            new_name='IPAddress',
        ),
        migrations.RemoveIndex(
            model_name='events',
            name='netvis_tran_srcport_74ac8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='events',
            name='netvis_tran_dstport_0c47b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='events',
            name='netvis_tran_src_ip__8c8cd2_idx',
        ),
        migrations.RemoveIndex(
            model_name='events',
            name='netvis_tran_dst_ip__768402_idx',
        ),
        migrations.RemoveIndex(
            model_name='events',
            name='netvis_tran_src_ip__e4517d_idx',
        ),
        migrations.RemoveIndex(
            model_name='ipaddress',
            name='netvis_ip_a_ip_vers_570485_idx',
        ),
        migrations.RemoveIndex(
            model_name='ipaddress',
            name='netvis_ip_a_cidr_d16da3_idx',
        ),
        migrations.RemoveIndex(
            model_name='ipaddress',
            name='netvis_ip_a_ip_addr_c38382_idx',
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['src_ip_id', 'dst_ip_id', 'protocol'], name='netvis_even_src_ip__ea251f_idx'),
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['dst_ip_id'], name='netvis_even_dst_ip__6454f9_idx'),
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['src_ip_id', 'dst_ip_id', 'srcport', 'dstport'], name='netvis_even_src_ip__67311d_idx'),
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['srcport', 'dstport'], name='netvis_even_srcport_62fd8e_idx'),
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['dstport'], name='netvis_even_dstport_f38c89_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['ip_version', 'ip_address', 'is_local'], name='netvis_ipad_ip_vers_28cb65_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['cidr'], name='netvis_ipad_cidr_3f713b_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['ip_address'], name='netvis_ipad_ip_addr_5bce38_idx'),
        ),
    ]
