# Generated by Django 4.0 on 2022-01-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netvis', '0012_alter_ipaddress_ip_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='subnet_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['subnet_name'], name='netvis_ipad_subnet__bc3dff_idx'),
        ),
    ]
